package signals

var (
	AppReady                  = New[any]("app_ready")
	RequestStarted            = New[any]("request_started")
	RequestFinished           = New[any]("request_finished")
	GotRequestException       = New[error]("got_request_exception")
	PreSave                   = New[any]("pre_save")
	PostSave                  = New[any]("post_save")
	PreDelete                 = New[any]("pre_delete")
	PostDelete                = New[any]("post_delete")
	ManyToManyChanged         = New[any]("many_to_many_changed")
	UserLoggedIn              = New[any]("user_logged_in")
	UserLoggedOut             = New[any]("user_logged_out")
	UserLoginFailed           = New[any]("user_login_failed")
	SettingsChanged           = New[any]("settings_changed")
	TemplateRendered          = New[any]("template_rendered")
	DatabaseConnectionCreated = New[any]("database_connection_created")
	PreMigrate                = New[any]("pre_migrate")
	PostMigrate               = New[any]("post_migrate")
	CheckRegistered           = New[any]("check_registered")
)
